#Python project

#load libraries

In [34]:
import pandas as pd

#Load dataset

In [ ]:
df = pd.read_csv("/content/sales_csv.csv")
print(df)

        Order_ID  Order_Date       Product     Category      Region  Quantity  \
0      ORD-09420  12/22/2025  Office Chair    Furniture      Lahore         2
1      ORD-08769   7/19/2025          Desk    Furniture      Multan         6
2      ORD-07657    8/8/2025        Laptop  Electronics    Peshawar         9
3      ORD-00417    3/2/2025        Laptop  Electronics      Multan         2
4      ORD-03711  12/12/2025        Laptop  Electronics      Multan        10
...          ...         ...           ...          ...         ...       ...
10015  ORD-05735    6/5/2025        Webcam  Accessories  Faisalabad         4
10016  ORD-05192   2/20/2025      Keyboard  Accessories  Rawalpindi        10
10017  ORD-05391   7/23/2025       Printer       Office      Lahore        10
10018  ORD-00861   8/21/2025       Monitor  Electronics     Karachi         4
10019  ORD-07271   1/29/2025  Office Chair    Furniture     Karachi        10

       Unit_Price  Unit_Cost Sales_Channel Payment_Method Salesperson  \
0          273.75     134.38     Corporate  Bank Transfer        Sara
1          682.28     387.99        Online  Bank Transfer        Hina
2         1148.24     659.54        Online  Bank Transfer       Hamza
3         1075.39     958.97  Retail Store  Bank Transfer         NaN
4         1250.18     986.51        Online    Credit Card        Zoya
...           ...        ...           ...            ...         ...
10015       63.30      28.15  Retail Store     Debit Card        Sara
10016       99.01      62.20        Online           Cash      Ayesha
10017      376.85     281.01     Corporate  Bank Transfer       Usman
10018      522.32     242.68     Corporate       JazzCash      Ayesha
10019      224.74     120.61  Retail Store  Bank Transfer       Bilal

          Sales  Total_Cost   Profit  Profit_Margin
0        547.50      268.76   278.74          50.91
1       4093.68     2327.94  1765.74          43.13
2      10334.16     5935.86  4398.30          42.56
3       2150.78     1917.94   232.84          10.83
4      12501.80     9865.10  2636.70          21.09
...         ...         ...      ...            ...
10015    253.20      112.60   140.60          55.53
10016    990.10      622.00   368.10          37.18
10017   3768.50     2810.10   958.40          25.43
10018   2089.28      970.72  1118.56          53.54
10019   2247.40     1206.10  1041.30          46.33

[10020 rows x 15 columns]

#Data Understanding

In [ ]:
df.head()

,Order_ID,Order_Date,Product,Category,Region,Quantity,Unit_Price,Unit_Cost,Sales_Channel,Payment_Method,Salesperson,Sales,Total_Cost,Profit,Profit_Margin
0,ORD-09420,12/22/2025,Office Chair,Furniture,Lahore,2,273.75,134.38,Corporate,Bank Transfer,Sara,547.50,268.76,278.74,50.91
1,ORD-08769,7/19/2025,Desk,Furniture,Multan,6,682.28,387.99,Online,Bank Transfer,Hina,4093.68,2327.94,1765.74,43.13
2,ORD-07657,8/8/2025,Laptop,Electronics,Peshawar,9,1148.24,659.54,Online,Bank Transfer,Hamza,10334.16,5935.86,4398.30,42.56
3,ORD-00417,3/2/2025,Laptop,Electronics,Multan,2,1075.39,958.97,Retail Store,Bank Transfer,NaN,2150.78,1917.94,232.84,10.83
4,ORD-03711,12/12/2025,Laptop,Electronics,Multan,10,1250.18,986.51,Online,Credit Card,Zoya,12501.80,9865.10,2636.70,21.09

In [ ]:
df.tail()

,Order_ID,Order_Date,Product,Category,Region,Quantity,Unit_Price,Unit_Cost,Sales_Channel,Payment_Method,Salesperson,Sales,Total_Cost,Profit,Profit_Margin
10015,ORD-05735,6/5/2025,Webcam,Accessories,Faisalabad,4,63.30,28.15,Retail Store,Debit Card,Sara,253.20,112.60,140.60,55.53
10016,ORD-05192,2/20/2025,Keyboard,Accessories,Rawalpindi,10,99.01,62.20,Online,Cash,Ayesha,990.10,622.00,368.10,37.18
10017,ORD-05391,7/23/2025,Printer,Office,Lahore,10,376.85,281.01,Corporate,Bank Transfer,Usman,3768.50,2810.10,958.40,25.43
10018,ORD-00861,8/21/2025,Monitor,Electronics,Karachi,4,522.32,242.68,Corporate,JazzCash,Ayesha,2089.28,970.72,1118.56,53.54
10019,ORD-07271,1/29/2025,Office Chair,Furniture,Karachi,10,224.74,120.61,Retail Store,Bank Transfer,Bilal,2247.40,1206.10,1041.30,46.33

In [ ]:
df.dtypes

Order_ID           object
Order_Date         object
Product            object
Category           object
Region             object
Quantity            int64
Unit_Price        float64
Unit_Cost         float64
Sales_Channel      object
Payment_Method     object
Salesperson        object
Sales             float64
Total_Cost        float64
Profit            float64
Profit_Margin     float64
dtype: object

In [ ]:
df.columns

Index(['Order_ID', 'Order_Date', 'Product', 'Category', 'Region', 'Quantity',
       'Unit_Price', 'Unit_Cost', 'Sales_Channel', 'Payment_Method',
       'Salesperson', 'Sales', 'Total_Cost', 'Profit', 'Profit_Margin'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=10020, step=1)

In [ ]:
df.shape

(10020, 15)

In [ ]:
df.describe()

,Quantity,Unit_Price,Unit_Cost,Sales,Total_Cost,Profit,Profit_Margin
count,10020.000000,10020.000000,10020.000000,10020.000000,10020.000000,10020.000000,10020.000000
mean,5.495010,376.344344,233.888658,2065.039369,1283.502664,781.536706,39.410109
std,2.879639,339.208375,235.130185,2376.603723,1612.781055,989.730825,17.897426
min,1.000000,20.020000,10.000000,20.140000,10.010000,3.280000,10.000000
25%,3.000000,110.707500,59.752500,479.587500,261.735000,168.420000,24.810000
50%,5.000000,283.260000,171.280000,1202.550000,693.530000,418.260000,37.700000
75%,8.000000,490.987500,295.605000,2725.087500,1667.722500,980.535000,52.600000
max,10.000000,1499.290000,1147.610000,14991.400000,11357.900000,9079.600000,87.330000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10020 entries, 0 to 10019
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        10020 non-null  object
 1   Order_Date      10020 non-null  object
 2   Product         10020 non-null  object
 3   Category        10020 non-null  object
 4   Region          10020 non-null  object
 5   Quantity        10020 non-null  int64
 6   Unit_Price      10020 non-null  float64
 7   Unit_Cost       10020 non-null  float64
 8   Sales_Channel   10020 non-null  object
 9   Payment_Method  9980 non-null   object
 10  Salesperson     9980 non-null   object
 11  Sales           10020 non-null  float64
 12  Total_Cost      10020 non-null  float64
 13  Profit          10020 non-null  float64
 14  Profit_Margin   10020 non-null  float64
dtypes: float64(6), int64(1), object(8)
memory usage: 1.1+ MB

In [ ]:
df.nunique()

Order_ID          10000
Order_Date          365
Product              12
Category              4
Region                8
Quantity             10
Unit_Price         9268
Unit_Cost          8847
Sales_Channel         3
Payment_Method        5
Salesperson          10
Sales              9783
Total_Cost         9621
Profit             9409
Profit_Margin      5112
dtype: int64

#Data Cleaning

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
duplicates =df.duplicated().sum()
print(duplicates)

20

In [ ]:
df.isnull().sum()

Order_ID           0
Order_Date         0
Product            0
Category           0
Region             0
Quantity           0
Unit_Price         0
Unit_Cost          0
Sales_Channel      0
Payment_Method    40
Salesperson       40
Sales              0
Total_Cost         0
Profit             0
Profit_Margin      0
dtype: int64

In [ ]:
null = df.isnull().sum()
print(null)

Order_ID           0
Order_Date         0
Product            0
Category           0
Region             0
Quantity           0
Unit_Price         0
Unit_Cost          0
Sales_Channel      0
Payment_Method    40
Salesperson       40
Sales              0
Total_Cost         0
Profit             0
Profit_Margin      0
dtype: int64

In [ ]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")

In [ ]:
df.dtypes

Order_ID                  object
Order_Date        datetime64[ns]
Product                   object
Category                  object
Region                    object
Quantity                   int64
Unit_Price               float64
Unit_Cost                float64
Sales_Channel             object
Payment_Method            object
Salesperson               object
Sales                    float64
Total_Cost               float64
Profit                   float64
Profit_Margin            float64
dtype: object

#DATA HANDLING

In [ ]:
print(df)

        Order_ID Order_Date       Product     Category      Region  Quantity  \
0      ORD-09420 2025-12-22  Office Chair    Furniture      Lahore         2
1      ORD-08769 2025-07-19          Desk    Furniture      Multan         6
2      ORD-07657 2025-08-08        Laptop  Electronics    Peshawar         9
3      ORD-00417 2025-03-02        Laptop  Electronics      Multan         2
4      ORD-03711 2025-12-12        Laptop  Electronics      Multan        10
...          ...        ...           ...          ...         ...       ...
10015  ORD-05735 2025-06-05        Webcam  Accessories  Faisalabad         4
10016  ORD-05192 2025-02-20      Keyboard  Accessories  Rawalpindi        10
10017  ORD-05391 2025-07-23       Printer       Office      Lahore        10
10018  ORD-00861 2025-08-21       Monitor  Electronics     Karachi         4
10019  ORD-07271 2025-01-29  Office Chair    Furniture     Karachi        10

       Unit_Price  Unit_Cost Sales_Channel Payment_Method Salesperson  \
0          273.75     134.38     Corporate  Bank Transfer        Sara
1          682.28     387.99        Online  Bank Transfer        Hina
2         1148.24     659.54        Online  Bank Transfer       Hamza
3         1075.39     958.97  Retail Store  Bank Transfer         NaN
4         1250.18     986.51        Online    Credit Card        Zoya
...           ...        ...           ...            ...         ...
10015       63.30      28.15  Retail Store     Debit Card        Sara
10016       99.01      62.20        Online           Cash      Ayesha
10017      376.85     281.01     Corporate  Bank Transfer       Usman
10018      522.32     242.68     Corporate       JazzCash      Ayesha
10019      224.74     120.61  Retail Store  Bank Transfer       Bilal

          Sales  Total_Cost   Profit  Profit_Margin
0        547.50      268.76   278.74          50.91
1       4093.68     2327.94  1765.74          43.13
2      10334.16     5935.86  4398.30          42.56
3       2150.78     1917.94   232.84          10.83
4      12501.80     9865.10  2636.70          21.09
...         ...         ...      ...            ...
10015    253.20      112.60   140.60          55.53
10016    990.10      622.00   368.10          37.18
10017   3768.50     2810.10   958.40          25.43
10018   2089.28      970.72  1118.56          53.54
10019   2247.40     1206.10  1041.30          46.33

[10020 rows x 15 columns]

In [ ]:
#VARIABLES
total_sales = df["Sales"].sum()
total_cost = df["Total_Cost"].sum()
total_profit = df["Profit"].sum()

In [ ]:
#list
product = df["Product"].tolist()
print(product [:10])
print(len(product))

['Office Chair', 'Desk', 'Laptop', 'Laptop', 'Laptop', 'Printer', 'Wireless Mouse', 'Desk', 'Office Chair', 'External SSD']
10020

In [ ]:
#dictionary
summary = {
    "total_sales": df["Sales"].sum(),
    "total_profit": df["Profit"].sum(),
    "total_orders": df["Order_ID"].nunique()
}

print(summary)

{'total_sales': np.float64(20691694.48), 'total_profit': np.float64(7830997.79), 'total_orders': 10000}

In [ ]:
#set
regions = df['Region'].tolist()
unique_regions = set(regions)
print(unique_regions)

{'Karachi', 'Multan', 'Islamabad', 'Faisalabad', 'Lahore', 'Rawalpindi', 'Sialkot', 'Peshawar'}

In [66]:
# Loop

unique_regions = set(regions)

for region in unique_regions:
    print(region)

Karachi
Multan
Islamabad
Faisalabad
Lahore
Rawalpindi
Sialkot
Peshawar

#functions

In [ ]:
df.columns

Index(['Order_ID', 'Order_Date', 'Product', 'Category', 'Region', 'Quantity',
       'Unit_Price', 'Unit_Cost', 'Sales_Channel', 'Payment_Method',
       'Salesperson', 'Sales', 'Total_Cost', 'Profit', 'Profit_Margin'],
      dtype='object')

In [ ]:
def calculate_sales(df):
  return df["Sales"].sum()
def calculate_cost(df):
  return  df["Total_Cost"].sum()
def calculate_profit(df):
   return df["Profit"].sum()
def highest_sale(df):
  return df["Sales"].max()
def lowest_sale(df):
  return df["Sales"].min()
def average_sale(df):
  return df["Sales"].mean()

print("Total Sales:", calculate_sales(df))
print("Total Cost:", calculate_cost(df))
print("Total Profit:", calculate_profit(df))
print("Highest Sale:", highest_sale(df))
print("Lowest Sale:", lowest_sale(df))
print("Average Sale:", average_sale(df))

Total Sales: 20691694.48
Total Cost: 12860696.690000001
Total Profit: 7830997.79
Highest Sale: 14991.4
Lowest Sale: 20.14
Average Sale: 2065.039369261477

#Exception / robust handling

In [ ]:
#invlid dtype
df["Sales"] = pd.to_numeric(df["Sales"], errors = "coerce")

In [ ]:
#misising values
df.isnull().sum()

Order_ID           0
Order_Date         0
Product            0
Category           0
Region             0
Quantity           0
Unit_Price         0
Unit_Cost          0
Sales_Channel      0
Payment_Method    40
Salesperson       40
Sales              0
Total_Cost         0
Profit             0
Profit_Margin      0
dtype: int64

In [ ]:
#replace misising values
df["Payment_Method"] = df["Payment_Method"].fillna(0)
df["Salesperson"] = df["Salesperson"].fillna(0)

In [ ]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Product           0
Category          0
Region            0
Quantity          0
Unit_Price        0
Unit_Cost         0
Sales_Channel     0
Payment_Method    0
Salesperson       0
Sales             0
Total_Cost        0
Profit            0
Profit_Margin     0
dtype: int64

In [31]:
#incorrect user input
try :
     value = float(input(" please enter a number"))
     print(value)
except:
  print(" invalid value entered")

 invalid value entered

In [36]:
#calculation errors
profit = 500
sale = 0
if sale != 0:
  margin = (profit/sale)
else:
  margin = "undefined"
print(margin)

undefined

#Remember: robust code detects problems, handles them deliberately, and verifies the result.

#FILE Handling

In [37]:
df.to_csv("cleaned_sales.csv", index=False)

print("Cleaned CSV saved!")

Cleaned CSV saved!

In [40]:
df.columns

Index(['Order_ID', 'Order_Date', 'Product', 'Category', 'Region', 'Quantity',
       'Unit_Price', 'Unit_Cost', 'Sales_Channel', 'Payment_Method',
       'Salesperson', 'Sales', 'Total_Cost', 'Profit', 'Profit_Margin'],
      dtype='object')

In [41]:
import json
summary = {
    "total_sales": df["Sales"].sum(),
    "total_cost": df["Total_Cost"].sum(),
    "total_profit": df["Profit"].sum(),
    "total_orders": df["Order_ID"].nunique()
}

with open("sales_summary.json", "w") as file:
    json.dump(summary, file, indent=4)

print("JSON summary saved!")

JSON summary saved!

#data transformation

In [42]:
df["Order_Year"] = df["Order_Date"].dt.year
df["Order_Month"] = df["Order_Date"].dt.month
df["Order_Day"] = df["Order_Date"].dt.day

#Filtering and sorting

In [46]:
#high value orders
high_value_orders = df[df["Sales"]>10000]
print(high_value_orders)

       Order_ID Order_Date     Product     Category      Region  Quantity  \
2     ORD-07657 2025-08-08      Laptop  Electronics    Peshawar         9
4     ORD-03711 2025-12-12      Laptop  Electronics      Multan        10
65    ORD-07415 2025-10-10      Laptop  Electronics    Peshawar        10
132   ORD-08505 2025-07-12  Smartphone  Electronics  Faisalabad        10
196   ORD-06841 2025-01-30  Smartphone  Electronics  Rawalpindi        10
...         ...        ...         ...          ...         ...       ...
9762  ORD-04434 2025-07-22      Laptop  Electronics   Islamabad        10
9825  ORD-04390 2025-10-02  Smartphone  Electronics  Rawalpindi        10
9862  ORD-08902 2025-04-24      Laptop  Electronics      Lahore        10
9976  ORD-02613 2025-08-26      Laptop  Electronics     Sialkot         9
9998  ORD-08667 2025-03-12  Smartphone  Electronics      Lahore        10

      Unit_Price  Unit_Cost Sales_Channel Payment_Method Salesperson  \
2        1148.24     659.54        Online  Bank Transfer       Hamza
4        1250.18     986.51        Online    Credit Card        Zoya
65       1340.88     999.20     Corporate  Bank Transfer       Usman
132      1044.88     555.61     Corporate       JazzCash       Maham
196      1008.50     632.88     Corporate           Cash       Usman
...          ...        ...           ...            ...         ...
9762     1188.10     930.26        Online              0      Ayesha
9825     1183.59     785.67        Online     Debit Card       Usman
9862     1229.19     751.65        Online       JazzCash       Bilal
9976     1450.56    1116.49     Corporate  Bank Transfer      Danish
9998     1116.77     279.80  Retail Store     Debit Card        Hina

         Sales  Total_Cost   Profit  Profit_Margin  Order_Year  Order_Month  \
2     10334.16     5935.86  4398.30          42.56        2025            8
4     12501.80     9865.10  2636.70          21.09        2025           12
65    13408.80     9992.00  3416.80          25.48        2025           10
132   10448.80     5556.10  4892.70          46.83        2025            7
196   10085.00     6328.80  3756.20          37.25        2025            1
...        ...         ...      ...            ...         ...          ...
9762  11881.00     9302.60  2578.40          21.70        2025            7
9825  11835.90     7856.70  3979.20          33.62        2025           10
9862  12291.90     7516.50  4775.40          38.85        2025            4
9976  13055.04    10048.41  3006.63          23.03        2025            8
9998  11167.70     2798.00  8369.70          74.95        2025            3

      Order_Day
2             8
4            12
65           10
132          12
196          30
...         ...
9762         22
9825          2
9862         24
9976         26
9998         12

[202 rows x 18 columns]

In [48]:
#low profit orders
low_profit_orders = df[df["Profit"]<100]
print(low_profit_orders)

        Order_ID Order_Date         Product     Category      Region  \
5      ORD-04783 2025-01-04         Printer       Office     Karachi
6      ORD-04095 2025-09-02  Wireless Mouse  Accessories     Karachi
15     ORD-08694 2025-05-02  Wireless Mouse  Accessories   Islamabad
18     ORD-06931 2025-04-20      Headphones  Accessories  Rawalpindi
19     ORD-00851 2025-09-14          Webcam  Accessories      Lahore
...          ...        ...             ...          ...         ...
9992   ORD-09168 2025-01-04          Webcam  Accessories  Faisalabad
9994   ORD-02048 2025-04-09         Printer       Office  Rawalpindi
9999   ORD-06397 2025-09-20        Keyboard  Accessories     Sialkot
10004  ORD-05052 2025-09-28        Keyboard  Accessories     Sialkot
10008  ORD-00770 2025-12-23  Wireless Mouse  Accessories  Rawalpindi

       Quantity  Unit_Price  Unit_Cost Sales_Channel Payment_Method  \
5             1      181.37     146.14  Retail Store     Debit Card
6             5       38.48      19.42     Corporate       JazzCash
15            1       67.31      34.85  Retail Store       JazzCash
18            1      202.93     119.61     Corporate  Bank Transfer
19            2       57.81      28.58     Corporate       JazzCash
...         ...         ...        ...           ...            ...
9992          7       56.24      43.64     Corporate    Credit Card
9994          1      359.40     298.72  Retail Store           Cash
9999          1       42.77      24.72     Corporate  Bank Transfer
10004         5       42.27      31.70        Online           Cash
10008         8       22.29      17.37     Corporate  Bank Transfer

      Salesperson   Sales  Total_Cost  Profit  Profit_Margin  Order_Year  \
5          Danish  181.37      146.14   35.23          19.42        2025
6             Ali  192.40       97.10   95.30          49.53        2025
15            Ali   67.31       34.85   32.46          48.22        2025
18           Sara  202.93      119.61   83.32          41.06        2025
19          Maham  115.62       57.16   58.46          50.56        2025
...           ...     ...         ...     ...            ...         ...
9992       Ayesha  393.68      305.48   88.20          22.40        2025
9994        Hamza  359.40      298.72   60.68          16.88        2025
9999        Bilal   42.77       24.72   18.05          42.20        2025
10004       Maham  211.35      158.50   52.85          25.01        2025
10008         Ali  178.32      138.96   39.36          22.07        2025

       Order_Month  Order_Day
5                1          4
6                9          2
15               5          2
18               4         20
19               9         14
...            ...        ...
9992             1          4
9994             4          9
9999             9         20
10004            9         28
10008           12         23

[1516 rows x 18 columns]

#Specific region / product / category / channel

In [49]:
region_orders = df[df["Region"] == "Lahore"]
product_orders = df[df["Product"] == "Laptop"]
category_orders = df[df["Category"] == "Electronics"]
channel_orders = df[df["Sales_Channel"] == "Online"]

In [50]:
#sorting
df.sort_values("Sales", ascending=False)

,Order_ID,Order_Date,Product,Category,Region,Quantity,Unit_Price,Unit_Cost,Sales_Channel,Payment_Method,Salesperson,Sales,Total_Cost,Profit,Profit_Margin,Order_Year,Order_Month,Order_Day
5311,ORD-07883,2025-01-23,Laptop,Electronics,Karachi,10,1499.14,938.06,Online,Credit Card,Usman,14991.40,9380.60,5610.80,37.43,2025,1,23
804,ORD-08879,2025-07-05,Laptop,Electronics,Peshawar,10,1480.72,896.76,Corporate,Debit Card,Hina,14807.20,8967.60,5839.60,39.44,2025,7,5
3559,ORD-08896,2025-08-29,Laptop,Electronics,Rawalpindi,10,1479.60,1115.14,Online,Credit Card,Usman,14796.00,11151.40,3644.60,24.63,2025,8,29
8757,ORD-07070,2025-04-01,Laptop,Electronics,Islamabad,10,1464.63,709.01,Online,Bank Transfer,Zoya,14646.30,7090.10,7556.20,51.59,2025,4,1
6044,ORD-09856,2025-06-11,Laptop,Electronics,Sialkot,10,1457.51,1030.72,Online,Debit Card,Hina,14575.10,10307.20,4267.90,29.28,2025,6,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4173,ORD-09936,2025-02-27,Wireless Mouse,Accessories,Rawalpindi,1,22.43,17.13,Retail Store,Credit Card,Hina,22.43,17.13,5.30,23.63,2025,2,27
5514,ORD-06577,2025-01-08,Wireless Mouse,Accessories,Peshawar,1,22.27,11.89,Corporate,JazzCash,Danish,22.27,11.89,10.38,46.61,2025,1,8
5258,ORD-07437,2025-08-11,Wireless Mouse,Accessories,Lahore,1,21.65,18.37,Corporate,Debit Card,Maham,21.65,18.37,3.28,15.15,2025,8,11
2724,ORD-01169,2025-03-26,Wireless Mouse,Accessories,Rawalpindi,1,21.58,11.08,Online,Debit Card,Zoya,21.58,11.08,10.50,48.66,2025,3,26
4838,ORD-09694,2025-04-08,Wireless Mouse,Accessories,Islamabad,1,20.14,11.68,Corporate,JazzCash,Hamza,20.14,11.68,8.46,42.01,2025,4,8

In [51]:
#lowest profit first
df.sort_values("Profit", ascending=True)

,Order_ID,Order_Date,Product,Category,Region,Quantity,Unit_Price,Unit_Cost,Sales_Channel,Payment_Method,Salesperson,Sales,Total_Cost,Profit,Profit_Margin,Order_Year,Order_Month,Order_Day
5258,ORD-07437,2025-08-11,Wireless Mouse,Accessories,Lahore,1,21.65,18.37,Corporate,Debit Card,Maham,21.65,18.37,3.28,15.15,2025,8,11
7721,ORD-07354,2025-07-15,Wireless Mouse,Accessories,Islamabad,1,24.98,20.74,Online,Cash,Zoya,24.98,20.74,4.24,16.97,2025,7,15
6053,ORD-04317,2025-08-03,Wireless Mouse,Accessories,Peshawar,1,27.68,22.78,Retail Store,Debit Card,Danish,27.68,22.78,4.90,17.70,2025,8,3
4093,ORD-03917,2025-01-10,Wireless Mouse,Accessories,Islamabad,1,22.79,17.62,Corporate,Cash,Maham,22.79,17.62,5.17,22.69,2025,1,10
4173,ORD-09936,2025-02-27,Wireless Mouse,Accessories,Rawalpindi,1,22.43,17.13,Retail Store,Credit Card,Hina,22.43,17.13,5.30,23.63,2025,2,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9616,ORD-05238,2025-01-06,Smartphone,Electronics,Rawalpindi,10,1116.71,262.00,Corporate,JazzCash,Hamza,11167.10,2620.00,8547.10,76.54,2025,1,6
2169,ORD-09540,2025-09-07,Smartphone,Electronics,Multan,10,1194.86,327.09,Online,Credit Card,Maham,11948.60,3270.90,8677.70,72.63,2025,9,7
7021,ORD-01111,2025-01-16,Smartphone,Electronics,Islamabad,10,1181.80,307.89,Corporate,Bank Transfer,Bilal,11818.00,3078.90,8739.10,73.95,2025,1,16
1618,ORD-01145,2025-02-11,Smartphone,Electronics,Peshawar,10,1191.93,309.54,Online,JazzCash,Zoya,11919.30,3095.40,8823.90,74.03,2025,2,11
5443,ORD-03407,2025-06-09,Smartphone,Electronics,Karachi,10,1131.25,223.29,Online,Bank Transfer,Sara,11312.50,2232.90,9079.60,80.26,2025,6,9

In [52]:
# Top 10 rows by sales
df.sort_values("Sales", ascending=False).head(10)

,Order_ID,Order_Date,Product,Category,Region,Quantity,Unit_Price,Unit_Cost,Sales_Channel,Payment_Method,Salesperson,Sales,Total_Cost,Profit,Profit_Margin,Order_Year,Order_Month,Order_Day
5311,ORD-07883,2025-01-23,Laptop,Electronics,Karachi,10,1499.14,938.06,Online,Credit Card,Usman,14991.4,9380.6,5610.8,37.43,2025,1,23
804,ORD-08879,2025-07-05,Laptop,Electronics,Peshawar,10,1480.72,896.76,Corporate,Debit Card,Hina,14807.2,8967.6,5839.6,39.44,2025,7,5
3559,ORD-08896,2025-08-29,Laptop,Electronics,Rawalpindi,10,1479.60,1115.14,Online,Credit Card,Usman,14796.0,11151.4,3644.6,24.63,2025,8,29
8757,ORD-07070,2025-04-01,Laptop,Electronics,Islamabad,10,1464.63,709.01,Online,Bank Transfer,Zoya,14646.3,7090.1,7556.2,51.59,2025,4,1
6044,ORD-09856,2025-06-11,Laptop,Electronics,Sialkot,10,1457.51,1030.72,Online,Debit Card,Hina,14575.1,10307.2,4267.9,29.28,2025,6,11
7687,ORD-09727,2025-08-21,Laptop,Electronics,Islamabad,10,1443.17,934.51,Retail Store,Debit Card,Danish,14431.7,9345.1,5086.6,35.25,2025,8,21
530,ORD-06602,2025-11-04,Laptop,Electronics,Karachi,10,1442.74,717.83,Retail Store,JazzCash,Bilal,14427.4,7178.3,7249.1,50.25,2025,11,4
9648,ORD-00005,2025-10-05,Laptop,Electronics,Karachi,10,1435.87,1039.19,Retail Store,Debit Card,Usman,14358.7,10391.9,3966.8,27.63,2025,10,5
3874,ORD-01098,2025-12-29,Laptop,Electronics,Karachi,10,1425.99,1106.17,Online,Bank Transfer,Hamza,14259.9,11061.7,3198.2,22.43,2025,12,29
9026,ORD-00537,2025-02-04,Laptop,Electronics,Peshawar,10,1425.18,726.79,Online,Cash,Usman,14251.8,7267.9,6983.9,49.00,2025,2,4

#KPI Analysis

In [53]:
total_sales = df["Sales"].sum()
total_cost = df["Total_Cost"].sum()
total_profit = df["Profit"].sum()

total_orders = df["Order_ID"].nunique()

average_order_value = (
    total_sales / total_orders
    if total_orders != 0
    else 0
)

highest_order = df["Sales"].max()
lowest_order = df["Sales"].min()

average_profit = df["Profit"].mean()
average_profit_margin = df["Profit_Margin"].mean()

print("Total Sales:", total_sales)
print("Total Cost:", total_cost)
print("Total Profit:", total_profit)
print("Average Order Value:", average_order_value)
print("Highest Order:", highest_order)
print("Lowest Order:", lowest_order)
print("Total Orders:", total_orders)
print("Average Profit:", average_profit)
print("Average Profit Margin:", average_profit_margin)

Total Sales: 20691694.48
Total Cost: 12860696.690000001
Total Profit: 7830997.79
Average Order Value: 2069.169448
Highest Order: 14991.4
Lowest Order: 20.14
Total Orders: 10000
Average Profit: 781.5367055888223
Average Profit Margin: 39.410108782435124

#Group Analysis

In [57]:
#Sales by Region
sales_by_region = df.groupby("Region")["Sales"].sum()
print(sales_by_region)
#Profit by Region
profit_by_region = df.groupby("Region")["Profit"].sum()
print(profit_by_region)
#Sales by Product
sales_by_product = df.groupby("Product")["Sales"].sum()
print(sales_by_product)
#Profit by Product
profit_by_product = df.groupby("Product")["Profit"].sum()
print(profit_by_product)
#Sales by Category
sales_by_category = df.groupby("Category")["Sales"].sum()
print(sales_by_category)
#Sales by Channel
sales_by_channel = df.groupby("Sales_Channel")["Sales"].sum()
print(sales_by_channel)
#Salesperson Performance
salesperson_performance = df.groupby("Salesperson")["Sales"].sum().sort_values(ascending=False).head(3)
print(salesperson_performance)

Region
Faisalabad    2547145.06
Islamabad     2532571.35
Karachi       2694193.57
Lahore        2434256.02
Multan        2712251.82
Peshawar      2582396.47
Rawalpindi    2628208.27
Sialkot       2560671.92
Name: Sales, dtype: float64
Region
Faisalabad     948358.20
Islamabad      943597.73
Karachi       1010363.33
Lahore         942225.18
Multan        1021584.60
Peshawar       972299.65
Rawalpindi    1016695.34
Sialkot        975873.76
Name: Profit, dtype: float64
Product
Desk              2086290.90
External SSD       826249.65
Headphones         646576.02
Keyboard           360418.34
Laptop            5326129.99
Monitor           1816233.39
Office Chair      1352066.07
Printer           1534161.21
Smartphone        3606978.37
Tablet            2399624.55
Webcam             488709.56
Wireless Mouse     248256.43
Name: Sales, dtype: float64
Product
Desk               841807.74
External SSD       344938.34
Headphones         310946.41
Keyboard           163899.10
Laptop            1526487.85
Monitor            662547.88
Office Chair       561659.03
Printer            604105.16
Smartphone        1508761.79
Tablet             942502.56
Webcam             237814.44
Wireless Mouse     125527.49
Name: Profit, dtype: float64
Category
Accessories     1743960.35
Electronics    13975215.95
Furniture       3438356.97
Office          1534161.21
Name: Sales, dtype: float64
Sales_Channel
Corporate       6995387.67
Online          7058784.48
Retail Store    6637522.33
Name: Sales, dtype: float64
Salesperson
Zoya     2342334.10
Maham    2297988.59
Usman    2150483.40
Name: Sales, dtype: float64

#Ranking

In [58]:
#Top 10 orders
top_10_orders = df.nlargest(10,"Sales")
print(top_10_orders)

       Order_ID Order_Date Product     Category      Region  Quantity  \
5311  ORD-07883 2025-01-23  Laptop  Electronics     Karachi        10
804   ORD-08879 2025-07-05  Laptop  Electronics    Peshawar        10
3559  ORD-08896 2025-08-29  Laptop  Electronics  Rawalpindi        10
8757  ORD-07070 2025-04-01  Laptop  Electronics   Islamabad        10
6044  ORD-09856 2025-06-11  Laptop  Electronics     Sialkot        10
7687  ORD-09727 2025-08-21  Laptop  Electronics   Islamabad        10
530   ORD-06602 2025-11-04  Laptop  Electronics     Karachi        10
9648  ORD-00005 2025-10-05  Laptop  Electronics     Karachi        10
3874  ORD-01098 2025-12-29  Laptop  Electronics     Karachi        10
9026  ORD-00537 2025-02-04  Laptop  Electronics    Peshawar        10

      Unit_Price  Unit_Cost Sales_Channel Payment_Method Salesperson    Sales  \
5311     1499.14     938.06        Online    Credit Card       Usman  14991.4
804      1480.72     896.76     Corporate     Debit Card        Hina  14807.2
3559     1479.60    1115.14        Online    Credit Card       Usman  14796.0
8757     1464.63     709.01        Online  Bank Transfer        Zoya  14646.3
6044     1457.51    1030.72        Online     Debit Card        Hina  14575.1
7687     1443.17     934.51  Retail Store     Debit Card      Danish  14431.7
530      1442.74     717.83  Retail Store       JazzCash       Bilal  14427.4
9648     1435.87    1039.19  Retail Store     Debit Card       Usman  14358.7
3874     1425.99    1106.17        Online  Bank Transfer       Hamza  14259.9
9026     1425.18     726.79        Online           Cash       Usman  14251.8

      Total_Cost  Profit  Profit_Margin  Order_Year  Order_Month  Order_Day
5311      9380.6  5610.8          37.43        2025            1         23
804       8967.6  5839.6          39.44        2025            7          5
3559     11151.4  3644.6          24.63        2025            8         29
8757      7090.1  7556.2          51.59        2025            4          1
6044     10307.2  4267.9          29.28        2025            6         11
7687      9345.1  5086.6          35.25        2025            8         21
530       7178.3  7249.1          50.25        2025           11          4
9648     10391.9  3966.8          27.63        2025           10          5
3874     11061.7  3198.2          22.43        2025           12         29
9026      7267.9  6983.9          49.00        2025            2          4

In [59]:
#top 5 products
top_5_products = df.groupby("Product")["Sales"].sum().sort_values(ascending=False).head(5)
print(top_5_products)
#

Product
Laptop        5326129.99
Smartphone    3606978.37
Tablet        2399624.55
Desk          2086290.90
Monitor       1816233.39
Name: Sales, dtype: float64

In [60]:
#top sales person
top_salesperson = (
    df.groupby("Salesperson")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(1)
)

print(top_salesperson)

Salesperson
Zoya    2342334.1
Name: Sales, dtype: float64

In [61]:
#Best region
best_region = (
    df.groupby("Region")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(1)
)

print(best_region)
#Best category
best_category = (
    df.groupby("Category")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(1)
)

print(best_category)
#Most profitable product
most_profitable_product = (
    df.groupby("Product")["Profit"]
    .sum()
    .sort_values(ascending=False)
    .head(1)
)

print(most_profitable_product)

Region
Multan    2712251.82
Name: Sales, dtype: float64
Category
Electronics    13975215.95
Name: Sales, dtype: float64
Product
Laptop    1526487.85
Name: Profit, dtype: float64

#FINAL BUSINESS REPORT

FINAL BUSINESS REPORT
Bring the entire workflow together:
RAW DATA
   ↓
INSPECT
   ↓
CLEAN
   ↓
TRANSFORM / VALIDATE
   ↓
CALCULATE KPIs
   ↓
FILTER & SORT
   ↓
GROUP ANALYSIS
   ↓
RANKING
   ↓
BUSINESS INSIGHTS
   ↓
EXPORT
Your final report should answer questions such as:
•	What are total sales, cost and profit?
•	How many unique orders are there?
•	Which region generates the most sales?
•	Which region generates the most profit?
•	Which products sell the most?
•	Which products are most profitable?
•	Which category performs best?
•	Which sales channel performs best?
•	Who is the top salesperson?
•	Are there high-value orders with low profit?
•	What important business patterns or problems did you find?

In [62]:
# Cleaned dataset
df.to_csv("cleaned_sales.csv", index=False)

# JSON summary
summary = {
    "total_sales": df["Sales"].sum(),
    "total_cost": df["Total_Cost"].sum(),
    "total_profit": df["Profit"].sum(),
    "total_orders": df["Order_ID"].nunique(),
    "average_profit": df["Profit"].mean(),
    "average_profit_margin": df["Profit_Margin"].mean()
}

with open("sales_summary.json", "w") as file:
    json.dump(summary, file, indent=4)

print("All outputs exported successfully!")

All outputs exported successfully!